### ISSUE TITLE
u-sm-hidden ?

### ISSUE THREAD

**Issue by cmnstmntmn** [suitcss/utils-display#12]
why this utility doesn't have responssiveness in mind ? or ..
is there another way to change `display` property of elements, based on media queries, inside suit utilities ?!

**Comment by simonsmith** [comment]
See #6 for previous discussion. Trivial to add yourself if needed.

Using the example from the other issue:

``` css
/* utils-display.css */

@import "suitcss-utils-display";

@media (--sm-max-viewport) {
  .u-sm-hidden { display: none !important; }
}

@media (--md-max-viewport) {
  .u-md-hidden { display: none !important; }
}

@media (--lg-max-viewport) {
  .u-lg-hidden { display: none !important; }
}
```
