### ISSUE TITLE
Add responsive versions

### ISSUE THREAD

**Issue by necolas** [suitcss/utils-display#6]
`u-sm-inline`, `u-md-inlineBlock`, `u-lg-block`, etc.

**Comment by racse1** [comment]
:thumbsup: It'll be very useful! Thanks.

**Comment by timkelty** [comment]
Use cases like this seem fairly common to me:

```
<div class="Header">
  <nav class="u-sm-hidden">
    <a href="/...">One</a>
    <a href="/...">Two</a>
    <a href="/...">Three</a>
  </nav>
  <a href="#menu" class="u-hidden u-sm-block">Hamburger Menu</a>
</div>
```

**Comment by simonsmith** [comment]
I'd probably make that a `Nav` component that was able to control the display of its descendants. I find it useful to do it that way because some times components need to define media queries that sit outside the site wide ones for grids etc

**Comment by timkelty** [comment]
@simonsmith Yeah, same here, but the utilities can be nice if they happen to be the same.

**Comment by AntonTrollback** [comment]
Not sure about this anymore.
I want to hide stuff without having to worry about adding the correct visible display value again.

Sometimes end up with utils like these:

```css
@media (--sm-max-viewport) {
  .u-sm-hide { display: none !important; }
}

@media (--md-max-viewport) {
  .u-md-hide { display: none !important; }
}

@media (--lg-max-viewport) {
  .u-lg-hide { display: none !important; }
}
```
